blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/krushndayshmookh/whisp/discussions
    about: Ask questions, share ideas, and discuss Whisp with the community
  - name: 📖 Documentation
    url: https://github.com/krushndayshmookh/whisp/wiki
    about: Check our documentation for setup guides, API references, and more
  - name: 🔒 Security Issues
    url: mailto:krushn@dayshmookh.com?subject=Security%20Vulnerability
    about: Report security vulnerabilities privately via email
  - name: 💡 Feature Ideas
    url: https://github.com/krushndayshmookh/whisp/discussions/categories/ideas
    about: Share feature ideas and suggestions in our discussions
